# vit_train.py
#
# HomeVerse — Task 1: Room Classification
#
# Input:
#   HomeVerse-QA/
#   ├── images/
#   │   ├── train/
#   │   ├── validation/
#   │   └── test/
#   └── annotations/
#       ├── train.json
#       ├── validation.json
#       └── test.json
#
# Each JSON file contains a list of image annotations generated by
# homeverse_generate.py.
#
# Task:
#   Floor-plan room crop -> ViT -> room class
#
# Model:
#   google/vit-base-patch16-224
#
# Usage:
#   python vit_train.py --data-root HomeVerse-QA --epochs 5
#
# Dry run:
#   python vit_train.py --data-root HomeVerse-QA --dry-run
#
# Recommended first test:
#   python vit_train.py --data-root HomeVerse-QA \
#       --epochs 1 \
#       --batch-size 8 \
#       --max-train-samples 100 \
#       --max-val-samples 50


import argparse
import json
import os
import random
from pathlib import Path

import numpy as np
import torch
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoImageProcessor,
    AutoModelForImageClassification,
)
from tqdm import tqdm
from sklearn.metrics import classification_report, confusion_matrix


# ============================================================
# Configuration
# ============================================================

MODEL_NAME = "google/vit-base-patch16-224"

ROOM_CLASSES = [
    "Living Room",
    "Kitchen",
    "Dining Room",
    "Kitchen & Dining",
    "Master Bedroom",
    "Bedroom",
    "Children's Bedroom",
    "Guest Bedroom",
    "Bathroom",
    "Toilet",
    "Study Room",
    "Office",
    "Utility Room",
    "Laundry Room",
    "Balcony",
    "Terrace",
    "Corridor",
    "Entrance/Foyer",
    "Storage Room",
    "Walk-in Closet",
    "Garage",
    "Staircase",
]

LABEL2ID = {
    label: idx
    for idx, label in enumerate(ROOM_CLASSES)
}

ID2LABEL = {
    idx: label
    for label, idx in LABEL2ID.items()
}


# ============================================================
# Reproducibility
# ============================================================

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


# ============================================================
# Dataset
# ============================================================

class HomeVerseRoomDataset(Dataset):
    """
    Converts image-level HomeVerse annotations into
    room-level classification samples.

    One floor-plan image containing N rooms produces N samples.

    Each sample contains:

        image
        room_type
        room_id
        layout_id
        scale_mode
        difficulty
        style
    """

    def __init__(
        self,
        data_root,
        split,
        processor,
        max_samples=None,
        padding_ratio=0.03,
    ):
        self.data_root = Path(data_root)
        self.split = split
        self.processor = processor
        self.padding_ratio = padding_ratio
        self._image_cache = {}

        annotation_path = (
            self.data_root
            / "annotations"
            / f"{split}.json"
        )

        if not annotation_path.exists():
            raise FileNotFoundError(
                f"Annotation file not found:\n{annotation_path}"
            )

        with open(annotation_path, "r", encoding="utf-8") as f:
            image_annotations = json.load(f)

        self.samples = []

        for annotation in image_annotations:

            image_path = (
                self.data_root
                / annotation["image_path"]
            )

            # image_path is stored relative to dataset root.
            if not image_path.exists():
                raise FileNotFoundError(
                    f"Image referenced by annotation does not exist:\n"
                    f"{image_path}"
                )

            image_width = annotation["image"]["width"]
            image_height = annotation["image"]["height"]

            for room in annotation["rooms"]:

                room_type = room["type"]

                if room_type not in LABEL2ID:
                    raise ValueError(
                        f"Unknown room class: {room_type}"
                    )

                bbox = room["bbox"]

                # Normalized [x, y, width, height]
                x = bbox["x"]
                y = bbox["y"]
                w = bbox["width"]
                h = bbox["height"]

                # Convert normalized coordinates -> pixels.
                x0 = x * image_width
                y0 = y * image_height
                x1 = (x + w) * image_width
                y1 = (y + h) * image_height

                # Small padding around the room.
                pad_x = (x1 - x0) * padding_ratio
                pad_y = (y1 - y0) * padding_ratio

                x0 = max(0, int(x0 - pad_x))
                y0 = max(0, int(y0 - pad_y))
                x1 = min(image_width, int(x1 + pad_x))
                y1 = min(image_height, int(y1 + pad_y))

                if x1 <= x0 or y1 <= y0:
                    continue

                self.samples.append({
                    "image_path": str(image_path),

                    "crop_box": (
                        x0,
                        y0,
                        x1,
                        y1,
                    ),

                    "label": LABEL2ID[room_type],

                    "room_type": room_type,
                    "room_id": room["id"],

                    "layout_id": annotation["layout_id"],

                    "scale_mode": annotation["scale_mode"],
                    "difficulty": annotation["difficulty"],
                    "style": annotation["style"],

                    "dimensions": room["dimensions"],
                })

                if (
                    max_samples is not None
                    and len(self.samples) >= max_samples
                ):
                    break

            if (
                max_samples is not None
                and len(self.samples) >= max_samples
            ):
                break

        if len(self.samples) == 0:
            raise RuntimeError(
                f"No room samples found for split '{split}'."
            )

        print(
            f"[{split}] image annotations: "
            f"{len(image_annotations)}"
        )

        print(
            f"[{split}] room samples: "
            f"{len(self.samples)}"
        )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, index):

        sample = self.samples[index]

        image_path = sample["image_path"]
        if image_path not in self._image_cache:
            self._image_cache[image_path] = Image.open(
                image_path
            ).convert("RGB")

        image = self._image_cache[image_path]

        crop = image.crop(
            sample["crop_box"]
        )

        encoded = self.processor(
            images=crop,
            return_tensors="pt",
        )

        # Processor returns:
        #
        # [1, 3, 224, 224]
        #
        # Remove batch dimension.
        pixel_values = encoded["pixel_values"].squeeze(0)

        return {
            "pixel_values": pixel_values,
            "labels": torch.tensor(
                sample["label"],
                dtype=torch.long,
            ),
        }


# ============================================================
# Metrics
# ============================================================

def calculate_accuracy(predictions, labels):

    predictions = np.asarray(predictions)
    labels = np.asarray(labels)

    return float(
        (predictions == labels).mean()
    )


def calculate_per_class_accuracy(
    predictions,
    labels,
):
    predictions = np.asarray(predictions)
    labels = np.asarray(labels)

    results = {}

    for class_id, class_name in ID2LABEL.items():

        mask = labels == class_id

        if mask.sum() == 0:
            results[class_name] = None
            continue

        results[class_name] = float(
            (predictions[mask] == labels[mask]).mean()
        )

    return results


# ============================================================
# Training
# ============================================================

def train_one_epoch(
    model,
    dataloader,
    optimizer,
    scheduler,
    device,
    epoch,
):

    model.train()

    total_loss = 0.0
    predictions = []
    labels = []

    progress = tqdm(
        dataloader,
        desc=f"Train {epoch}",
    )

    for batch in progress:

        pixel_values = batch["pixel_values"].to(device)
        batch_labels = batch["labels"].to(device)

        optimizer.zero_grad(
            set_to_none=True
        )

        outputs = model(
            pixel_values=pixel_values,
            labels=batch_labels,
        )

        loss = outputs.loss

        loss.backward()

        optimizer.step()

        if scheduler is not None:
            scheduler.step()

        total_loss += loss.item()

        logits = outputs.logits

        batch_predictions = (
            torch.argmax(
                logits,
                dim=-1,
            )
        )

        predictions.extend(
            batch_predictions.detach()
            .cpu()
            .numpy()
            .tolist()
        )

        labels.extend(
            batch_labels.detach()
            .cpu()
            .numpy()
            .tolist()
        )

        accuracy = calculate_accuracy(
            predictions,
            labels,
        )

        progress.set_postfix(
            loss=f"{loss.item():.4f}",
            accuracy=f"{accuracy:.4f}",
        )

    average_loss = (
        total_loss / len(dataloader)
    )

    accuracy = calculate_accuracy(
        predictions,
        labels,
    )

    return average_loss, accuracy


# ============================================================
# Validation
# ============================================================

@torch.no_grad()
def evaluate(
    model,
    dataloader,
    device,
):

    model.eval()

    total_loss = 0.0

    predictions = []
    labels = []

    for batch in tqdm(
        dataloader,
        desc="Validation",
    ):

        pixel_values = batch["pixel_values"].to(device)
        batch_labels = batch["labels"].to(device)

        outputs = model(
            pixel_values=pixel_values,
            labels=batch_labels,
        )

        total_loss += outputs.loss.item()

        batch_predictions = (
            torch.argmax(
                outputs.logits,
                dim=-1,
            )
        )

        predictions.extend(
            batch_predictions.cpu()
            .numpy()
            .tolist()
        )

        labels.extend(
            batch_labels.cpu()
            .numpy()
            .tolist()
        )

    average_loss = (
        total_loss / len(dataloader)
    )

    accuracy = calculate_accuracy(
        predictions,
        labels,
    )

    per_class = calculate_per_class_accuracy(
        predictions,
        labels,
    )

    report_dict = classification_report(
        labels,
        predictions,
        target_names=[ID2LABEL[i] for i in range(len(ROOM_CLASSES))],
        labels=list(range(len(ROOM_CLASSES))),
        output_dict=True,
        zero_division=0,
    )

    report_text = classification_report(
        labels,
        predictions,
        target_names=[ID2LABEL[i] for i in range(len(ROOM_CLASSES))],
        labels=list(range(len(ROOM_CLASSES))),
        zero_division=0,
    )

    cm = confusion_matrix(
        labels,
        predictions,
        labels=list(range(len(ROOM_CLASSES))),
    ).tolist()

    return (
        average_loss,
        accuracy,
        per_class,
        report_dict,
        cm,
        report_text,
    )


# ============================================================
# Main
# ============================================================

def main():

    parser = argparse.ArgumentParser(
        description="HomeVerse ViT Task 1 training"
    )

    parser.add_argument(
        "--data-root",
        type=Path,
        required=True,
    )

    parser.add_argument(
        "--model",
        default=MODEL_NAME,
    )

    parser.add_argument(
        "--epochs",
        type=int,
        default=5,
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=16,
    )

    parser.add_argument(
        "--learning-rate",
        type=float,
        default=2e-5,
    )

    parser.add_argument(
        "--weight-decay",
        type=float,
        default=0.01,
    )

    parser.add_argument(
        "--num-workers",
        type=int,
        default=0,
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=2026,
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(
            "ml/dimension-vit/checkpoints"
        ),
    )

    parser.add_argument(
        "--max-train-samples",
        type=int,
        default=None,
    )

    parser.add_argument(
        "--max-val-samples",
        type=int,
        default=None,
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
    )

    args = parser.parse_args()

    # --------------------------------------------------------
    # Seed
    # --------------------------------------------------------

    set_seed(args.seed)

    # --------------------------------------------------------
    # Device
    # --------------------------------------------------------

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    print()
    print("=" * 60)
    print("HomeVerse ViT — Task 1")
    print("=" * 60)

    print(
        f"Model:  {args.model}"
    )

    print(
        f"Device: {device}"
    )

    if torch.cuda.is_available():
        print(
            f"GPU:    "
            f"{torch.cuda.get_device_name(0)}"
        )

    print("=" * 60)
    print()

    # --------------------------------------------------------
    # Processor
    # --------------------------------------------------------

    processor = (
        AutoImageProcessor.from_pretrained(
            args.model
        )
    )

    # --------------------------------------------------------
    # Dataset
    # --------------------------------------------------------

    train_dataset = HomeVerseRoomDataset(
        data_root=args.data_root,
        split="train",
        processor=processor,
        max_samples=args.max_train_samples,
    )

    val_dataset = HomeVerseRoomDataset(
        data_root=args.data_root,
        split="validation",
        processor=processor,
        max_samples=args.max_val_samples,
    )

    # --------------------------------------------------------
    # DataLoader
    # --------------------------------------------------------

    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=torch.cuda.is_available(),
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=torch.cuda.is_available(),
    )

    print(
        f"Train batches: "
        f"{len(train_loader)}"
    )

    print(
        f"Validation batches: "
        f"{len(val_loader)}"
    )

    # --------------------------------------------------------
    # Model
    # --------------------------------------------------------

    model = (
        AutoModelForImageClassification
        .from_pretrained(
            args.model,

            num_labels=len(ROOM_CLASSES),

            id2label=ID2LABEL,
            label2id=LABEL2ID,

            ignore_mismatched_sizes=True,
        )
    )

    model.to(device)

    # --------------------------------------------------------
    # Dry run
    # --------------------------------------------------------

    if args.dry_run:

        print()
        print("Running dry-run...")
        print()

        batch = next(
            iter(train_loader)
        )

        pixel_values = (
            batch["pixel_values"]
            .to(device)
        )

        labels = (
            batch["labels"]
            .to(device)
        )

        print(
            "Input shape:",
            tuple(pixel_values.shape),
        )

        print(
            "Labels shape:",
            tuple(labels.shape),
        )

        with torch.no_grad():

            outputs = model(
                pixel_values=pixel_values,
                labels=labels,
            )

        print(
            "Logits shape:",
            tuple(outputs.logits.shape),
        )

        print(
            "Loss:",
            float(outputs.loss),
        )

        print()
        print("Dry-run successful.")
        print()

        return

    # --------------------------------------------------------
    # Optimizer
    # --------------------------------------------------------

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )

    # --------------------------------------------------------
    # Scheduler
    # --------------------------------------------------------

    total_steps = (
        len(train_loader)
        * args.epochs
    )

    scheduler = (
        torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer,
            T_max=total_steps,
        )
    )

    # --------------------------------------------------------
    # Output directory
    # --------------------------------------------------------

    args.output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    best_accuracy = -1.0

    history = []

    # --------------------------------------------------------
    # Training loop
    # --------------------------------------------------------

    for epoch in range(
        1,
        args.epochs + 1,
    ):

        print()
        print(
            f"========== Epoch {epoch}/"
            f"{args.epochs} =========="
        )

        train_loss, train_accuracy = (
            train_one_epoch(
                model=model,
                dataloader=train_loader,
                optimizer=optimizer,
                scheduler=scheduler,
                device=device,
                epoch=epoch,
            )
        )

        (
            val_loss,
            val_accuracy,
            per_class_accuracy,
            report_dict,
            cm,
            report_text,
        ) = evaluate(
            model=model,
            dataloader=val_loader,
            device=device,
        )

        macro_p = report_dict["macro avg"]["precision"]
        macro_r = report_dict["macro avg"]["recall"]
        macro_f1 = report_dict["macro avg"]["f1-score"]

        print()
        print(f"Train Loss:     {train_loss:.4f}")
        print(f"Train Accuracy: {train_accuracy:.4f}")
        print(f"Val Loss:       {val_loss:.4f}")
        print(f"Val Accuracy:   {val_accuracy:.4f}")
        print(f"Val Macro P:    {macro_p:.4f}")
        print(f"Val Macro R:    {macro_r:.4f}")
        print(f"Val Macro F1:   {macro_f1:.4f}")
        print()
        print("Classification Report:")
        print(report_text)

        history.append({
            "epoch": epoch,
            "train_loss": train_loss,
            "train_accuracy": train_accuracy,
            "val_loss": val_loss,
            "val_accuracy": val_accuracy,
            "val_macro_precision": macro_p,
            "val_macro_recall": macro_r,
            "val_macro_f1": macro_f1,
            "per_class_accuracy": per_class_accuracy,
            "classification_report": report_dict,
            "confusion_matrix": cm,
        })

        # ----------------------------------------------------
        # Save best checkpoint
        # ----------------------------------------------------

        if val_accuracy > best_accuracy:

            best_accuracy = val_accuracy

            checkpoint_dir = (
                args.output_dir
                / "best"
            )

            checkpoint_dir.mkdir(
                parents=True,
                exist_ok=True,
            )

            model.save_pretrained(
                checkpoint_dir
            )

            processor.save_pretrained(
                checkpoint_dir
            )

            with open(
                checkpoint_dir
                / "training_config.json",
                "w",
                encoding="utf-8",
            ) as f:

                json.dump(
                    {
                        "model": args.model,
                        "task": "room_classification",
                        "num_classes": len(
                            ROOM_CLASSES
                        ),
                        "best_val_accuracy":
                            best_accuracy,
                        "best_val_macro_f1":
                            macro_f1,
                        "seed": args.seed,
                    },
                    f,
                    indent=2,
                )

            with open(
                checkpoint_dir
                / "classification_report.json",
                "w",
                encoding="utf-8",
            ) as f:
                json.dump(report_dict, f, indent=2)

            with open(
                checkpoint_dir
                / "confusion_matrix.json",
                "w",
                encoding="utf-8",
            ) as f:
                json.dump({
                    "labels": [ID2LABEL[i] for i in range(len(ROOM_CLASSES))],
                    "matrix": cm,
                }, f, indent=2)

            print()
            print(
                f"New best checkpoint: "
                f"Accuracy: {best_accuracy:.4f} | Macro F1: {macro_f1:.4f}"
            )


    # --------------------------------------------------------
    # Training history
    # --------------------------------------------------------

    with open(
        args.output_dir
        / "training_history.json",
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            history,
            f,
            indent=2,
        )

    print()
    print("=" * 60)
    print("Training complete")
    print("=" * 60)

    print(
        f"Best validation accuracy: "
        f"{best_accuracy:.4f}"
    )

    print(
        f"Checkpoint: "
        f"{args.output_dir / 'best'}"
    )


if __name__ == "__main__":
    main()
