"""create_materials_table_v3

Revision ID: 4efce17eca3e
Revises: 9b313abdd02f
Create Date: 2026-09-06 16:28:18.304137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid


# revision identifiers, used by Alembic.
revision: str = '4efce17eca3e'
down_revision: Union[str, None] = '9b313abdd02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', app.db.guid.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('albedo_color', sa.String(), nullable=True),
    sa.Column('roughness', sa.Float(), nullable=True),
    sa.Column('metalness', sa.Float(), nullable=True),
    sa.Column('normal_scale', sa.Float(), nullable=True),
    sa.Column('cost_per_sqft', sa.Float(), nullable=True),
    sa.Column('texture_url', sa.String(), nullable=True),
    sa.Column('durability_rating', sa.Float(), nullable=True),
    sa.Column('maintenance_score', sa.Float(), nullable=True),
    sa.Column('eco_rating', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_name'))
        batch_op.drop_index(batch_op.f('ix_materials_category'))

    op.drop_table('materials')
    # ### end Alembic commands ###
