"""create_analytics_events_table

Revision ID: 9a6b51dd369f
Revises: 2b6d9f74160e
Create Date: 2026-09-05 18:10:29.083921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid


# revision identifiers, used by Alembic.
revision: str = '9a6b51dd369f'
down_revision: Union[str, None] = '2b6d9f74160e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', app.db.guid.GUID(), nullable=False),
    sa.Column('user_id', app.db.guid.GUID(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_event_name'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_created_at'))

    op.drop_table('analytics_events')
    # ### end Alembic commands ###
