"""add_v2_product_columns_and_notifications

Revision ID: 9b313abdd02f
Revises: 9a6b51dd369f
Create Date: 2026-09-06 12:14:55.309511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import app.db.guid


# revision identifiers, used by Alembic.
revision: str = '9b313abdd02f'
down_revision: Union[str, None] = '9a6b51dd369f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'notifications' not in tables:
        op.create_table(
            'notifications',
            sa.Column('id', app.db.guid.GUID(), nullable=False),
            sa.Column('user_id', app.db.guid.GUID(), nullable=True),
            sa.Column('project_id', app.db.guid.GUID(), nullable=True),
            sa.Column('title', sa.String(), nullable=False),
            sa.Column('message', sa.Text(), nullable=False),
            sa.Column('type', sa.String(), nullable=True),
            sa.Column('read', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimensions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('style', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('material', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('colour', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('colour')
        batch_op.drop_column('material')
        batch_op.drop_column('style')
        batch_op.drop_column('availability')
        batch_op.drop_column('rating')
        batch_op.drop_column('dimensions')

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'notifications' in inspector.get_table_names():
        op.drop_table('notifications')

    # ### end Alembic commands ###
