"""create_marketplace_tables_v4

Revision ID: b3a5f8c7b108
Revises: 4efce17eca3e
Create Date: 2026-09-06 21:09:20.434077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.guid


# revision identifiers, used by Alembic.
revision: str = 'b3a5f8c7b108'
down_revision: Union[str, None] = '4efce17eca3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', app.db.guid.GUID(), nullable=False),
    sa.Column('user_id', app.db.guid.GUID(), nullable=True),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('pricing_model', sa.String(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('portfolio', sa.JSON(), nullable=True),
    sa.Column('availability_status', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_listings',
    sa.Column('id', app.db.guid.GUID(), nullable=False),
    sa.Column('provider_id', app.db.guid.GUID(), nullable=True),
    sa.Column('listing_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('min_order_qty', sa.Integer(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('sample_available', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotations',
    sa.Column('id', app.db.guid.GUID(), nullable=False),
    sa.Column('project_id', app.db.guid.GUID(), nullable=False),
    sa.Column('provider_id', app.db.guid.GUID(), nullable=False),
    sa.Column('quotation_number', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_days', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('warranty_period_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', app.db.guid.GUID(), nullable=False),
    sa.Column('project_id', app.db.guid.GUID(), nullable=False),
    sa.Column('provider_id', app.db.guid.GUID(), nullable=False),
    sa.Column('quotation_id', app.db.guid.GUID(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('total_contract_value', sa.Float(), nullable=True),
    sa.Column('milestone_payment_schedule', sa.JSON(), nullable=True),
    sa.Column('client_signature', sa.String(), nullable=True),
    sa.Column('client_signed_at', sa.DateTime(), nullable=True),
    sa.Column('provider_signature', sa.String(), nullable=True),
    sa.Column('provider_signed_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    op.drop_table('quotations')
    op.drop_table('marketplace_listings')
    op.drop_table('providers')
    # ### end Alembic commands ###
