#!/usr/bin/env python3
"""
HomeVerse Database Migration CLI (Phase 37)
Provides unified Alembic migration operations across environments.
Usage:
  python scripts/migrate.py upgrade [revision]
  python scripts/migrate.py downgrade [revision]
  python scripts/migrate.py make "revision description"
  python scripts/migrate.py status
  python scripts/migrate.py check
"""
import os
import sys
from pathlib import Path
from alembic.config import Config
from alembic import command

# Locate project directories
ROOT_DIR = Path(__file__).resolve().parent.parent
BACKEND_DIR = ROOT_DIR / "backend"
ALEMBIC_INI = BACKEND_DIR / "alembic.ini"

# Ensure backend is in python path
sys.path.insert(0, str(BACKEND_DIR))

def get_alembic_config() -> Config:
    if not ALEMBIC_INI.exists():
        raise FileNotFoundError(f"Cannot find alembic.ini at {ALEMBIC_INI}")
    cfg = Config(str(ALEMBIC_INI))
    # Ensure working directory is backend for relative paths in alembic.ini
    cfg.set_main_option("here", str(BACKEND_DIR))
    return cfg

def upgrade(revision: str = "head"):
    cfg = get_alembic_config()
    print(f"--> Applying database migrations up to: {revision}...")
    command.upgrade(cfg, revision)
    print("--> Database schema upgraded successfully.")

def downgrade(revision: str = "-1"):
    cfg = get_alembic_config()
    print(f"--> Rolling back database migrations to: {revision}...")
    command.downgrade(cfg, revision)
    print("--> Database schema downgraded successfully.")

def make_migration(message: str):
    cfg = get_alembic_config()
    print(f"--> Generating new autogenerated migration: '{message}'...")
    command.revision(cfg, message=message, autogenerate=True)
    print("--> Migration script generated in database/migrations/versions/.")

def status():
    cfg = get_alembic_config()
    print("--> Current Database Revision:")
    command.current(cfg, verbose=True)
    print("\n--> Available Migration Heads:")
    command.heads(cfg, verbose=True)

def check():
    cfg = get_alembic_config()
    print("--> Checking model vs database schema sync...")
    command.check(cfg)
    print("--> Schema is completely in sync with models.")

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    cmd = sys.argv[1].lower()
    try:
        if cmd == "upgrade":
            rev = sys.argv[2] if len(sys.argv) > 2 else "head"
            upgrade(rev)
        elif cmd == "downgrade":
            rev = sys.argv[2] if len(sys.argv) > 2 else "-1"
            downgrade(rev)
        elif cmd in ["make", "revision", "generate"]:
            if len(sys.argv) < 3:
                print("Error: Migration message required. Example: python scripts/migrate.py make 'add table'")
                sys.exit(1)
            msg = sys.argv[2]
            make_migration(msg)
        elif cmd in ["status", "current", "heads"]:
            status()
        elif cmd == "check":
            check()
        else:
            print(f"Unknown command '{cmd}'. Available: upgrade, downgrade, make, status, check")
            sys.exit(1)
    except Exception as e:
        print(f"\n[ERROR] Migration operation failed: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
